### PR TITLE
Convert to a pip package

### PR DESCRIPTION
**Pull request by kousu**
Part of https://github.com/neuropoly/spinalcordtoolbox/issues/2669

### CODE REVIEW

**Comment by kousu** [comment]
To use, just go to /releases and make a new release or go to /actions and click Publish -> Run. The version tag you fill in in either case should be 'YEAR.MONTH.DAYrcN', e.g. 2021.04.04rc5.

**Comment by jcohenadad** [comment]
> To use, just go to /releases and make a new release or go to /actions and click Publish -> Run. The version tag you fill in in either case should be 'YEAR.MONTH.DAYrcN', e.g. 2021.04.04rc5.

i noticed that other releases were using another convention, without the zero: https://github.com/neuropoly/spinalcordtoolbox-data-deepseg_gm_models/releases/tag/2018.2.5
i suggest we always go for the ISO standard, ie: YYYYMMDD (with the zero)

**Comment by kousu** [comment]
> > To use, just go to /releases and make a new release or go to /actions and click Publish -> Run. The version tag you fill in in either case should be 'YEAR.MONTH.DAYrcN', e.g. 2021.04.04rc5.
> 
> i noticed that other releases were using another convention, without the zero: https://github.com/neuropoly/spinalcordtoolbox-data-deepseg_gm_models/releases/tag/2018.2.5
> i suggest we always go for the ISO standard, ie: YYYYMMDD (with the zero)

Thanks for that feedback! It was on my list of things to clarify.

pip forces us to use YYYY.MM.DD though. It also normalizes the format, so even if we put in 2020.04.09 it will be published to pypi as 2020.4.9.

**Comment by kousu** [comment]
The extremely tedious details are in https://www.python.org/dev/peps/pep-0440/#version-scheme

**Review by jcohenadad — APPROVED** [review]
difficult for me to review this (i don't understand the whole mechanics, and cannot test if it works), but i'll approve it anyway. I get the overall idea

**Pull request merged**
